### ISSUE TITLE
Suggestion for font imports

### ISSUE THREAD

**Issue by omenking** [davejfox/Origin#1]
Before

``` scss
h2 {
  font-family: 'gibson-semibold';
}
p {
  font-family: 'gibson-regular';
}
```

After

``` scss
h2 {
  font-family: Gibson;
  font-weight: 600;
}
p {
  font-family: Gibson;
  font-weight: 500;
}
```

example of import

``` scss
//  Web Fonts
@include fontwoff2('Gibson','gibson',normal,300); //light
@include fontwoff2('Gibson','gibson',normal,500); //regular
@include fontwoff2('Gibson','gibson',italic,500); //italic
@include fontwoff2('Gibson','gibson',normal,600); //semi-bold

@include font('Chaparral','chaparral',normal,500); //caption
@include font('Chaparral','chaparral',normal,300); //light
@include font('Chaparral','chaparral',italic,500); //italic
@include font('Chaparral','chaparral',normal,600); //semibold
```

Dem functions

``` scss
// eg. @include font(Open Sans,open-sans,italic,600)
//
// This will expect fonts to be in directory:
// _/fonts/<base>/<style>-<weight>
// eg. _/fonts/open-sans/italic-600.<ext>
//
@mixin font($name,$base,$style,$weight) {
  $dir: "_/fonts/" + $base + "/" + $style + "-" + $weight;
    @font-face {
        font-family: $name;
    font-weight: $weight;
    font-style:  $style;
        src: url($dir + ".eot");
        src: url($dir + ".eot?#iefix") format("embedded-opentype"),
             url($dir + ".woff") format("woff"),
             url($dir + ".ttf") format("truetype"),
             url($dir + ".svg#" + $name + "") format("svg");
    }   
}

@mixin fontwoff2($name,$base,$style,$weight) {
  $dir: "_/fonts/" + $base + "/" + $style + "-" + $weight;
    @font-face {
        font-family: $name;
    font-weight: $weight;
    font-style:  $style;
        src: url($dir + ".eot");
        src: url($dir + ".eot?#iefix") format("embedded-opentype"),
             url($dir + ".woff") format("woff"),
             url($dir + ".woff2") format("woff"),
             url($dir + ".ttf") format("truetype"),
             url($dir + ".svg#" + $name + "") format("svg");
    }   
```
