### ISSUE TITLE
Suggestion for defined vars for breakpoints

### ISSUE THREAD

**Issue by omenking** [davejfox/Origin#2]
It'd be nice to have vars defined by default in grid for up and only breakpoints

``` scss
// Additional grid sizes can be added here.
@include gridSize("xsmall", 0);
@include gridSize("small" , $smallScreen);
@include gridSize("medium", $mediumScreen);
@include gridSize("large" , $largeScreen);

$xsmall-up: "only screen and (min-width: 0px)";
$xsmall-only: "only screen and (min-width: 0px) and (max-width: #{$smallScreen + px})";


$small-up:  "only screen and (min-width: #{$smallScreen + px})";
$small-only: "only screen and (min-width: #{$smallScreen + px}) and (max-width: #{$mediumScreen + px})";

$medium-up: "only screen and (min-width: #{$mediumScreen + px})";
$medium-only: "only screen and (min-width: #{$mediumScreen + px}) and (max-width: #{$largeScreen + px})";

$large-up:  "only screen and (min-width: #{$largeScreen + px})";
$large-only: "only screen and (min-width: #{$smallScreen + px})";
```

So when you need to use a breakpoint you can just do this:

``` scss

@media #{$xsmall-only} {
  .header { background: rgb(255,0,0); }
}

@media #{$small-up} {
  .header { background: rgb(0,255,0); }
}


```
